import os
import json

path = r'C:\Users\ItzP\projects\opencode-pet\_stress_watcher.py'

code = []
code.append('"""')
code.append('OpenCode Pet -- File Watcher Stress Test Suite (task_0010)')
code.append('"""')
code.append('from __future__ import annotations')
code.append('')
code.append('import ctypes')
code.append('import json')
code.append('import os')
code.append('import random')
code.append('import shutil')
code.append('import sys')
code.append('import tempfile')
code.append('import threading')
code.append('import time')
code.append('import traceback')
code.append('from ctypes import wintypes')
code.append('')
code.append("sys.path.insert(0, r'C:\\Users\\ItzP\\projects\\opencode-pet')")
code.append('from desktop.main import read_dir_changes, PET_DIR, CONFIG_FILE')
code.append('')
code.append('kernel32 = ctypes.windll.kernel32')
code.append('')
code.append("PASS = 'PASS'")
code.append("FAIL = 'FAIL'")
code.append("WARN = 'WARN'")
code.append('')
code.append('results = []')
code.append('')
code.append('')
code.append('def log(test_id, verdict, detail):')
code.append('    results.append((test_id, verdict, detail))')
code.append("    icon = {PASS: '[PASS] ', FAIL: '[FAIL] ', WARN: '[WARN] '}.get(verdict, '[??] ')")
code.append('    print(f"  {icon}{test_id}: {detail}")')
code.append('')
code.append('')
code.append('def write_status(path, state="busy", size_bytes=200):')
code.append('    body = {')
code.append('        "sessionID": os.path.basename(path).replace("status-", "").replace(".json", ""),')
code.append('        "state": state,')
code.append('        "updatedAt": int(time.time() * 1000),')
code.append('        "toolLabel": "TestAgent",')
code.append('    }')
code.append('    data = json.dumps(body).encode()')
code.append('    if len(data) < size_bytes:')
code.append('        data += b" " * (size_bytes - len(data))')
code.append('    with open(path, "wb") as f:')
code.append('        f.write(data)')
code.append('')
code.append('')
code.append('def make_status_files(directory, n, state="busy"):')
code.append('    for i in range(n):')
code.append('        write_status(os.path.join(directory, f"status-{i:05d}.json"), state=state)')
code.append('')
with open(path, "w", encoding="utf-8") as f:')
code.append('    f.write(chr(10).join(code))')
code.append('print("Part 1 written, lines:", len(code))')

with open(os.path.join(os.path.dirname(path), '_write_part1.py'), 'w') as f:
    f.write(chr(10).join(code))
print('part1 script written')
